[2024-06-10T07:06:18.574+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T07:06:18.592+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_files_to_cloud_storage_dag.upload_files_to_cloud_storage_task manual__2024-06-10T07:06:17.500212+00:00 [queued]>
[2024-06-10T07:06:18.604+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_files_to_cloud_storage_dag.upload_files_to_cloud_storage_task manual__2024-06-10T07:06:17.500212+00:00 [queued]>
[2024-06-10T07:06:18.605+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-10T07:06:18.623+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_files_to_cloud_storage_task> on 2024-06-10 07:06:17.500212+00:00
[2024-06-10T07:06:18.632+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_files_to_cloud_storage_dag', 'upload_files_to_cloud_storage_task', 'manual__2024-06-10T07:06:17.500212+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/input.py', '--cfg-path', '/tmp/tmpk3fu2c16']
[2024-06-10T07:06:18.635+0000] {standard_task_runner.py:91} INFO - Job 139: Subtask upload_files_to_cloud_storage_task
[2024-06-10T07:06:18.637+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2092) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-10T07:06:18.638+0000] {standard_task_runner.py:63} INFO - Started process 2093 to run task
[2024-06-10T07:06:18.690+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_files_to_cloud_storage_dag.upload_files_to_cloud_storage_task manual__2024-06-10T07:06:17.500212+00:00 [running]> on host f69b53e362bb
[2024-06-10T07:06:18.781+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='upload_files_to_cloud_storage_dag' AIRFLOW_CTX_TASK_ID='upload_files_to_cloud_storage_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T07:06:17.500212+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T07:06:17.500212+00:00'
[2024-06-10T07:06:18.783+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T07:06:18.818+0000] {base.py:84} INFO - Using connection ID '***s3' for task execution.
[2024-06-10T07:06:18.820+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='***s3', conn_type='aws') credentials retrieved from extra.
[2024-06-10T07:06:19.249+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-10T07:06:19.250+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T07:06:19.259+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=upload_files_to_cloud_storage_dag, task_id=upload_files_to_cloud_storage_task, run_id=manual__2024-06-10T07:06:17.500212+00:00, execution_date=20240610T070617, start_date=20240610T070618, end_date=20240610T070619
[2024-06-10T07:06:19.295+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-10T07:06:19.315+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-10T07:06:19.319+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
