[2024-06-09T06:06:29.234+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T06:06:29.262+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_files_to_cloud_storage_dag.upload_files_to_cloud_storage_task manual__2024-06-09T06:06:27.124108+00:00 [queued]>
[2024-06-09T06:06:29.282+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_files_to_cloud_storage_dag.upload_files_to_cloud_storage_task manual__2024-06-09T06:06:27.124108+00:00 [queued]>
[2024-06-09T06:06:29.284+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-09T06:06:29.306+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_files_to_cloud_storage_task> on 2024-06-09 06:06:27.124108+00:00
[2024-06-09T06:06:29.316+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_files_to_cloud_storage_dag', 'upload_files_to_cloud_storage_task', 'manual__2024-06-09T06:06:27.124108+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/input.py', '--cfg-path', '/tmp/tmpyaijmm6z']
[2024-06-09T06:06:29.319+0000] {standard_task_runner.py:91} INFO - Job 125: Subtask upload_files_to_cloud_storage_task
[2024-06-09T06:06:29.329+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1989) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-09T06:06:29.332+0000] {standard_task_runner.py:63} INFO - Started process 1990 to run task
[2024-06-09T06:06:29.377+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_files_to_cloud_storage_dag.upload_files_to_cloud_storage_task manual__2024-06-09T06:06:27.124108+00:00 [running]> on host f69b53e362bb
[2024-06-09T06:06:29.504+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='upload_files_to_cloud_storage_dag' AIRFLOW_CTX_TASK_ID='upload_files_to_cloud_storage_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T06:06:27.124108+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T06:06:27.124108+00:00'
[2024-06-09T06:06:29.506+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T06:06:29.557+0000] {base.py:84} INFO - Using connection ID '***s3' for task execution.
[2024-06-09T06:06:29.558+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='***s3', conn_type='aws') credentials retrieved from extra.
[2024-06-09T06:06:30.393+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-09T06:06:30.394+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T06:06:30.405+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=upload_files_to_cloud_storage_dag, task_id=upload_files_to_cloud_storage_task, run_id=manual__2024-06-09T06:06:27.124108+00:00, execution_date=20240609T060627, start_date=20240609T060629, end_date=20240609T060630
[2024-06-09T06:06:30.473+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-09T06:06:30.500+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09T06:06:30.502+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
